name: Protobuf Compile
on:
  push:
    branches:
      - main
jobs:
  compile:
    name: Compile for Golang
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Protobuf event defs
        uses: actions/checkout@v2
        with:
          path: protobuf-defs
      - name: Checkout Golang event repo
        uses: actions/checkout@v2
        with:
          repository: tommzn/hdb-events-go
          ref: main
          path: golang-events
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Go Env Setup
        run: |
          export GOPATH=$HOME/go
          export GOBIN=$(go env GOPATH)/bin
          export PATH=$PATH:$GOPATH
          export PATH=$PATH:$GOBIN
          export GO111MODULE=on
      - name: Install Protobuf compiler
        run: |
          sudo apt-get install -y protobuf-compiler
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          protoc --version 
      - name: Compile
        run: protoc -I=protobuf-defs/ --go_out=golang-events/ protobuf-defs/*.proto
      - name: Debug 2
        run: cat golang-events/github.com/tommzn/hdb-events-go/weather.pb.go
