name: Protobuf Compile
on:
  push:
    branches:
      - main
jobs:
  compile:
    name: Compile for Golang
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Protobuf event defs
        uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Go Env Setup
        run: |
          export GOPATH=$HOME/go
          export GOBIN=$(go env GOPATH)/bin
          export PATH=$PATH:$GOPATH
          export PATH=$PATH:$GOBIN
          export GO111MODULE=on
      - name: Install Protobuf compiler
        run: |
          sudo apt-get install -y protobuf-compiler
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          protoc --version 
      - name: Compile
        run: protoc --go_out=./ *.proto
      - name: Upload Golang artifact
        uses: actions/upload-artifact@v2
        with:
          name: golang-events
          path: ./*.pb.go
          retention-days: 1

  deploy:
    name: Update HomeDashboard event lib
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - name: Checkout Protobuf event defs
        uses: actions/checkout@v2
        with:
          repository: tommzn/hdb-events-go
          ref: main
      - name: Download Golang events
        uses: actions/download-artifact@v2
        with:
          name: golang-events
      - name: Debug Log
        run: ls -al


