name: Protobuf Compile
on:
  push:
    branches:
      - main
jobs:
  compile:
    name: Compile for Golang
    runs-on: ubuntu-latest
    env:
      PROTOBUF_SRC_DIR: protobuf-defs
      PROTOBUF_DEST_GOLANG: protobuf-golang
      GOLANG_EVENTS_REPO: golang-events
    steps:
      - name: Checkout Protobuf event defs
        uses: actions/checkout@v2
        with:
          path: ${{ env.PROTOBUF_SRC_DIR }}
      - name: Checkout Golang event repo
        uses: actions/checkout@v2
        with:
          repository: tommzn/hdb-events-go
          ref: main
          path: ${{ env.GOLANG_EVENTS_REPO }}
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Go Env Setup
        run: |
          export GOPATH=$HOME/go
          export GOBIN=$(go env GOPATH)/bin
          export PATH=$PATH:$GOPATH
          export PATH=$PATH:$GOBIN
          export GO111MODULE=on
          mkdir -p ${{ env.PROTOBUF_DEST_GOLANG }}
      - name: Install Protobuf compiler
        run: |
          sudo apt-get install -y protobuf-compiler
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          protoc --version 
      - name: Compile
        run: protoc -I=${{ env.PROTOBUF_SRC_DIR }} --go_out=${{ env.PROTOBUF_DEST_GOLANG }} ${{ env.PROTOBUF_SRC_DIR }}/*.proto
      - name: Copy Golang Events
        run: find -iname '*.pb.go' -exec cp {} ${{ env.GOLANG_EVENTS_REPO }} \;
      - name: Debug 2
        run: ls -al ${{ env.GOLANG_EVENTS_REPO }}
