name: Protobuf Compile
on:
  push:
    branches:
      - main
jobs:
  compile:
    name: Compile for Golang
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Protobuf event defs
        uses: actions/checkout@v2
        with:
          path: protobuf-defs
      - name: Checkout Golang event repo
        uses: actions/checkout@v2
        with:
          repository: tommzn/hdb-events-go
          ref: main
          path: golang-events
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Go env
        run: go env
        env:
          GOBIN: ${{ env.GOPATH }}/bin
      - name: Go Path ls
        run: ls -al /home/runner/go
      - name: Go bin
        run: ls -al ${{ env.GOPATH }}/bin
      - name: Install Protobuf compiler
        run: go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
      - name: Compile
        run: protoc -I=protobuf-defs/ --go_out=golang-events/ *.proto
      - name: Go env 2
        run: go env
      - name: Debug 2
        run: ls -al golang-events/
