name: Protobuf Compile
on:
  push:
    branches:
      - main
jobs:
  compile:
    name: Compile for Golang
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Install Protobuf compiler
        run: go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
      - name: Compile
        run: protoc --go_out=src/go *.proto
      - name: Debug
        run: ls -al